<x-guest-layout>
    <html>

    <head>
        <meta content="text/html; charset=UTF-8" http-equiv="content-type">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{{ mix('css/app.css') }}" rel="stylesheet">
    </head>

    <body class="w-full p-5 md:max-w-[1200px] md:py-[60px] m-auto">
        <p class="text-white text-[24px] md:text-[40px] text-center font-bold">EARNINGS DISCLAIMER</p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            The offers do not in any way constitute any no projection of earnings, promises, or representations
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            By subscribing to Publisher&rsquo;s material, you expressly acknowledge and agree that we are in no way offering
            any promises, suggestions, projections, representations, or guarantees of any kind regarding future earnings
            prospects or earnings, and that we have not authorized any projections, promises, or representations from
            third parties, internal or external to the company.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            Any earnings statements or any examples of earnings, represent only estimates of what we think you can earn
            by applying the same principles as we do but there is no guarantee. Should you make investments on the
            estimate of any figure provided, you must accept the business risk and that you will not arrive at the same
            performance.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            This applies whether the profits or examples of income are monetary in nature or pertaining to claims of any
            kind that may be generated by the proposed activity (beyond their convertibility to cash or otherwise).
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            There is no guarantee that any previous successes or passive results relating to earnings or income (whether
            monetary or otherwise, convertible to cash or otherwise) will come true, nor can previous successes be used
            as an indication of your future success. Any claims or statements about income or earnings (whether monetary
            or otherwise, convertible to cash or otherwise) should not be considered &ldquo;average earnings” or &ldquo;earnings
            estimates.”
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            Here are some of both macroeconomic and microeconomic conditions that could affect your result
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            (i) The economy. The economy, whether local, national or even global in scale, creates additional
            uncertainty and economic risk for any business venture.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            An economic recession or depression could adversely affect the results produced.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            (ii) Attitude. Success in using the information or strategies provided on the site depends on a variety of
            factors, the first of which is undoubtedly attitude. We have no way of knowing how well you will do, since
            we do not know you, your background, work ethic, dedication, motivation, desire, or business skills or
            practices. Therefore, we do not guarantee or imply that you will get rich, do as well, or have certain
            earnings.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            Internet activities and profits come with unknown risks and are not suitable for everyone. You may not rely
            on any information presented on the Web site or otherwise provided by us unless you do so with the knowledge
            that you may lose your investment in full.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            (iii) Future Forecasts and Estimates. Materials contained on this Web site or in materials purchased and/or
            downloaded from this Web site may contain information that includes or is based on forward-looking
            statements. Forward-looking statements seek our expectations or predictions of future events. You can
            identify these statements by the fact that they do not strictly relate to historical or current facts and
            use words such as &ldquo;anticipate,” &ldquo;estimate,” &ldquo;expect,” &ldquo;project,” &ldquo;intend,” &ldquo;plan,” &ldquo;believe,” and other
            words and terms of similar meaning in connection with describing potential earnings or financial
            performance.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            Any statements of guidance in the alternative here, in other materials contained on this website, or in
            materials purchased and/or downloaded from this website, are intended to express our opinion regarding
            potential earnings. Many factors will be important in determining actual results, and no guarantee is made
            that results similar to those presented will be achieved.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            (iv) Due Diligence. You should perform due diligence on your company when making investment decisions and
            should use caution and seek the advice of qualified professionals. You should check with your accountant,
            lawyer or professional advisor or financial advisor before acting on the information you have gathered. You
            cannot consider any example, document or other content on the Web site or otherwise provided by us to be
            equivalent to professional or financial advice. Nothing contained on the Web site or in the materials
            available for sale or download on the Web site provides professional advice in any way. You should consult
            your accountant, attorney, professional advisor, or financial advisor with any questions you may have.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            Furthermore, the information on this website, on other related websites or on social profiles, does not in
            any way constitute &ldquo;investment advice” under Art. 1 c. 5 septies of Legislative Decree 58/98, for a number
            of reasons, among them: They are NOT personalized but are addressed to a wide audience and, therefore, are
            NOT provided knowing the characteristics of each individual user/visitor. Moreover, the same are not
            intended as investment recommendations, but simply the author&rsquo;s investment ideas and are generally provided
            for informational or educational purposes only. All articles on the site, social channels in which topics
            related to trading or investing in general or money management are discussed, have &ldquo;disclaimers” and
            &ldquo;alerts” that urge the user to inform himself as much as possible about the related risks.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            Before anything else, therefore, carefully read the disclaimers on social channels related to the community. Specifically,
            any information on this site, on any related and user-owned sites, and on any social channels is intended
            for informational, educational, or learning purposes only. Any named Software has no purpose other than to
            show the workings of the business cycle and computer automation possible through programmingBetween 74% and
            89% of people who enter the investment world lose money. You should consider understanding how the
            investment world works before investing and only investing what you can afford to lose.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            Past performance does not guarantee future performance.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            The marketing and communication activity of the brand &ldquo;James Trading Group” is managed by Fintech Media
            Advertising SA Calea Floreasca 169A, corp A, etaj 4, Bucuresti, Romania VAT:42738586The domain and trademark
            are owned byFintech Media Advertising SA Calea Floreasca 169A, corp A, etaj 4, Bucuresti, Romania
            VAT:42738586Any disputes regarding alleged violations and misleading communications to the marketing
            activity should be reported to the email address

            <span class="font-bold">complaints@fintechmediasa.ro</span>.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            This Agreement, the rights and obligations of the parties under this Agreement and any action or legal
            proceedings, whether arising directly or indirectly from this Contract, or related to the transactions
            contemplated by this Contract, shall be governed by, construed and enforced in accordance with the laws of
            the state of Romania FintechMedia adv. SA and the Client hereby submit irrevocably to the exclusive
            jurisdiction of the courts of Romania.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            &ldquo;James Trading Group” IS ALSO A PROVIDER OF STRATEGIES AND SIGNALS FOR MORDEX COPY TRADING SERVICES, ASSET
            MANAGER REGISTERED WITH THE CZECH NATIONAL BANK AND AUTHORIZED TO CARRY OUT EQUITY MANAGEMENT IN A WAY LIKE
            INVESTMENT FUND MANAGEMENT UNDER § 15 OF LAW NO. 240/2013 COLL. ON INVESTMENT COMPANIES AND INVESTMENT FUNDS
            (ZISIF).
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            CNB (CZECH NATIONAL BANK) LICENSE NUMBER: 19819145
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            THE SIGNALS OF &ldquo;James Trading Group” ARE MANAGED BY MORDEX IN ACCORDANCE WITH THE REGULATIONS APPLICABLE TO
            COPY TRADING/MIRROR TRADING SERVICES AND IN ACCORDANCE WITH ESMA Q&A 2012/382, QUESTION 9: ARTICLE 4(1)(9)
            OF MIFID – AUTOMATIC EXECUTION OF TRADING SIGNALS.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            THE ROLE OF &ldquo;James Trading Group” DIFFERS FROM THAT OF FINANCIAL ADVISER AND AS A PROVIDER OF TRADING
            SIGNALS/STRATEGIES DOES NOT HAVE THE POWER TO PROVIDE CONSULTATION IN INVESTMENT, FINANCIAL PROMOTIONS AND
            SOLICITATIONS.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            THE INFORMATION PROVIDED ON THIS SITE SHOULD NOT BE CONSIDERED AN INVESTMENT RECOMMENDATION OR SOLICITATION.
        </p>

        <p class="text-white text-[13px] md:text-[16px] leading-[120%] my-[10px] md:my-[12px]">
            &ldquo;James Trading Group” is a brand owned by Fintech Media Advertising SA Calea Floreasca 169A, corp A, etaj 4,
            Bucuresti, Romania VAT:42738586
        </p>
    </body>

    </html>
</x-guest-layout>
