<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class CreateNotificationLanguageKeysTable extends Migration
{
    public function up()
    {
        Schema::create('notification_language_keys', function (Blueprint $table) {
            $table->id();
            $table->string('notification_type');
            $table->string('language_key');
            $table->timestamps();
        });

        // Seed the database with initial data
        DB::table('notification_language_keys')->insert([
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'profit_achieve_notification_subject'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'profit_achieve_notification_hello'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'profit_achieve_notification_message'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'profit_achieve_notification_details'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'profit_achieve_notification_pro_minimum_balance'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'profit_achieve_notification_pro_plus_minimum_balance'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'profit_achieve_notification_contact_description'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'telegram_link'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'contact_on_telegram'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'best_regards'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'company_name'],
            ['notification_type' => 'ProfitAchievementNotification', 'language_key' => 'disclaimer'],

            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'profit_notification_forfree_prosetting_subject'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'hello'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'profit_notification_forfree_prosetting_message'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'profit_notification_forfree_prosetting_details'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'profit_notification_forfree_prosetting_instructions'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'profit_notification_forfree_prosetting_step1'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'profit_notification_forfree_prosetting_step1-link'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'profit_notification_forfree_prosetting_step1-label'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'profit_notification_forfree_prosetting_step2'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'profit_notification_forfree_prosetting_contact'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'telegram_link'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'contact_on_telegram'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'best_regards'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'company_name'],
            ['notification_type' => 'ProfitNotificationForFreeProSetting', 'language_key' => 'disclaimer'],

            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'profit_notification_high_setting_subject'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'hello'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'profit_notification_high_setting_deposit'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'profit_notification_high_setting_detail'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'profit_notification_high_setting_pro_minimum'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'profit_notification_high_setting_pro_plus_minimum'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'profit_notification_high_setting_higher'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'profit_notification_high_setting_switch'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'profit_notification_high_setting_deposit_contact'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'telegram_link'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'contact_on_telegram'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'best_regards'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'company_name'],
            ['notification_type' => 'ProfitNotificationForHighSettingDeposit', 'language_key' => 'disclaimer'],

            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'profit_notification_low_setting_subject'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'hello'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'profit_notification_low_setting_deposit'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'profit_notification_low_setting_medium_balance'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'profit_notification_low_setting_high_balance'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'profit_notification_low_setting_pro_pro'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'profit_notification_low_setting_pro_minimum'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'profit_notification_low_setting_pro_plus_minimum'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'profit_notification_low_setting_higher_more'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'profit_notification_low_setting_switch'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'profit_notification_low_setting_switch_deposit_contact'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'telegram_link'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'contact_on_telegram'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'best_regards'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'company_name'],
            ['notification_type' => 'ProfitNotificationForLowSettingDeposit', 'language_key' => 'disclaimer'],

            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'profit_notification_medium_setting_subject'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'hello'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'profit_notification_medium_setting_deposit'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'profit_notification_medium_setting_high_balance'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'profit_notification_medium_setting_pro_pro'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'profit_notification_medium_setting_pro_minimum'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'profit_notification_medium_setting_pro_plus_minimum'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'profit_notification_medium_setting_higher_more'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'profit_notification_medium_setting_switch'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'profit_notification_medium_setting_deposit_contact'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'telegram_link'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'contact_on_telegram'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'best_regards'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'company_name'],
            ['notification_type' => 'ProfitNotificationForMediumSettingDeposit', 'language_key' => 'disclaimer'],

            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'profit_notification_pro_plusplus_subject'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'hello'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'profit_notification_pro_plusplus_message'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'pro_plus_plus_plus_profit'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'pro_plus_plus_plus_purchase'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'buy_pro_plus_plus_plus_setting'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'pro_plus_plus_buy_setting_link'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'profit_notification_pro_plusplus_telegram'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'telegram_link'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'contact_on_telegram'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'best_regards'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'company_name'],
            ['notification_type' => 'ProfitNotificationForProPlusPlusSettingDeposit', 'language_key' => 'disclaimer'],

            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'profit_pro_plus_plus_plus_subject'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'hello'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'profit_notification_pro_plus_message'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'pro_plus_plus_profit'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'pro_plus_plus_purchase'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'buy_pro_plus_plus_setting'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'pro_plus_buy_setting_link'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'profit_notification_pro_plus_telegram'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'telegram_link'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'contact_on_telegram'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'best_regards'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'company_name'],
            ['notification_type' => 'ProfitNotificationForProPlusSettingDeposit', 'language_key' => 'disclaimer'],

            ['notification_type' => 'ProfitNotificationforProProPlusInvite', 'language_key' => 'profit_invite_subject'],
            ['notification_type' => 'ProfitNotificationforProProPlusInvite', 'language_key' => 'hello'],
            ['notification_type' => 'ProfitNotificationforProProPlusInvite', 'language_key' => 'profit_invite_description'],
            ['notification_type' => 'ProfitNotificationforProProPlusInvite', 'language_key' => 'profit_notification_invite_profit_details'],
            ['notification_type' => 'ProfitNotificationforProProPlusInvite', 'language_key' => 'profit_telegram'],
            ['notification_type' => 'ProfitNotificationforProProPlusInvite', 'language_key' => 'telegram_link'],
            ['notification_type' => 'ProfitNotificationforProProPlusInvite', 'language_key' => 'contact_on_telegram'],
            ['notification_type' => 'ProfitNotificationforProProPlusInvite', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'ProfitNotificationforProProPlusInvite', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'ProfitNotificationforProProPlusInvite', 'language_key' => 'best_regards'],
            ['notification_type' => 'ProfitNotificationforProProPlusInvite', 'language_key' => 'company_name'],
            ['notification_type' => 'ProfitNotificationforProProPlusInvite', 'language_key' => 'disclaimer'],

            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'profit_pro_plus_subject'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'hello'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'profit_notification_for_pro_deposit_message'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'pro_plus_profit'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'pro_plus_purchase'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'pro_buy_setting_link'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'profit_notification_for_pro_deposit_buy_pro_plus_setting'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'profit_notification_for_pro_deposit_telegram'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'telegram_link'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'contact_on_telegram'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'best_regards'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'company_name'],
            ['notification_type' => 'ProfitNotificationForProSettingDeposit', 'language_key' => 'disclaimer'],

            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'profit_pro_pro_plus_subject'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'hello'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'profit_congratulations_message'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'profit_details'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'pro_pro_plus_purchase'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'buy_pro_setting'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'buy_setting_link'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'buy_pro_setting_link'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'buy_pro_plus_setting'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'pro_pro_plus_telegram'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'telegram_link'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'contact_on_telegram'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'best_regards'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'company_name'],
            ['notification_type' => 'ProfitNotificationForProSettingPurchase', 'language_key' => 'disclaimer'],

            ['notification_type' => 'AccountSuccessfullyAdded', 'language_key' => 'new_account_added_subject'],
            ['notification_type' => 'AccountSuccessfullyAdded', 'language_key' => 'hello'],
            ['notification_type' => 'AccountSuccessfullyAdded', 'language_key' => 'view_details'],
            ['notification_type' => 'AccountSuccessfullyAdded', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'AccountSuccessfullyAdded', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'AccountSuccessfullyAdded', 'language_key' => 'best_regards'],
            ['notification_type' => 'AccountSuccessfullyAdded', 'language_key' => 'company_name'],
            ['notification_type' => 'AccountSuccessfullyAdded', 'language_key' => 'disclaimer'],

            ['notification_type' => 'AccountSuccessfullyConnected', 'language_key' => 'new_account_connected_subject'],
            ['notification_type' => 'AccountSuccessfullyConnected', 'language_key' => 'hello'],
            ['notification_type' => 'AccountSuccessfullyConnected', 'language_key' => 'account_connected_message'],
            ['notification_type' => 'AccountSuccessfullyConnected', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'AccountSuccessfullyConnected', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'AccountSuccessfullyConnected', 'language_key' => 'best_regards'],
            ['notification_type' => 'AccountSuccessfullyConnected', 'language_key' => 'company_name'],
            
            ['notification_type' => 'AccountSuccessfullyUpdated', 'language_key' => 'user_account_updated_subject'],
            ['notification_type' => 'AccountSuccessfullyUpdated', 'language_key' => 'hello'],
            ['notification_type' => 'AccountSuccessfullyUpdated', 'language_key' => 'user_account_updated_message'],
            ['notification_type' => 'AccountSuccessfullyUpdated', 'language_key' => 'email'],
            ['notification_type' => 'AccountSuccessfullyUpdated', 'language_key' => 'account'],
            ['notification_type' => 'AccountSuccessfullyUpdated', 'language_key' => 'password'],
            ['notification_type' => 'AccountSuccessfullyUpdated', 'language_key' => 'server'],
            ['notification_type' => 'AccountSuccessfullyUpdated', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'AccountSuccessfullyUpdated', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'AccountSuccessfullyUpdated', 'language_key' => 'best_regards'],
            ['notification_type' => 'AccountSuccessfullyUpdated', 'language_key' => 'company_name'],
            ['notification_type' => 'AccountSuccessfullyUpdated', 'language_key' => 'disclaimer'],

            ['notification_type' => 'AccountWasDeleted', 'language_key' => 'account_deleted_subject'],
            ['notification_type' => 'AccountWasDeleted', 'language_key' => 'hello'],
            ['notification_type' => 'AccountWasDeleted', 'language_key' => 'account_deleted_message'],
            ['notification_type' => 'AccountWasDeleted', 'language_key' => 'email'],
            ['notification_type' => 'AccountWasDeleted', 'language_key' => 'account'],
            ['notification_type' => 'AccountWasDeleted', 'language_key' => 'password'],
            ['notification_type' => 'AccountWasDeleted', 'language_key' => 'server'],
            ['notification_type' => 'AccountWasDeleted', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'AccountWasDeleted', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'AccountWasDeleted', 'language_key' => 'best_regards'],
            ['notification_type' => 'AccountWasDeleted', 'language_key' => 'company_name'],
            ['notification_type' => 'AccountWasDeleted', 'language_key' => 'disclaimer'],

            ['notification_type' => 'CleanupNotification', 'language_key' => 'hello'],
            ['notification_type' => 'CleanupNotification', 'language_key' => 'cleanup_message'],
            ['notification_type' => 'CleanupNotification', 'language_key' => 'clean_description'],
            ['notification_type' => 'CleanupNotification', 'language_key' => 'best_regards'],
            ['notification_type' => 'CleanupNotification', 'language_key' => 'company_name'],
            ['notification_type' => 'CleanupNotification', 'language_key' => 'disclaimer'],

            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'deposit_subject'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'hello'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'deposit_message'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'high_balance'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'pro_pro_plus_details'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'pro_minimum_balance'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'pro_plus_minimum_balance'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'higher_balance_more_profit'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'switch_high'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'deposit_contact_instruction'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'contact_on_telegram'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'best_regards'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'company_name'],
            ['notification_type' => 'DummyPnlNotification', 'language_key' => 'disclaimer'],

            ['notification_type' => 'LoginNotification', 'language_key' => 'login_subject'],
            ['notification_type' => 'LoginNotification', 'language_key' => 'login_greeting'],
            ['notification_type' => 'LoginNotification', 'language_key' => 'login_message'],
            ['notification_type' => 'LoginNotification', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'LoginNotification', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'LoginNotification', 'language_key' => 'best_regards'],
            ['notification_type' => 'LoginNotification', 'language_key' => 'company_name'],
            ['notification_type' => 'LoginNotification', 'language_key' => 'disclaimer'],

            ['notification_type' => 'UserCreatedNotification', 'language_key' => 'welcome_subject'],
            ['notification_type' => 'UserCreatedNotification', 'language_key' => 'hello'],
            ['notification_type' => 'UserCreatedNotification', 'language_key' => 'password_creation_message'],
            ['notification_type' => 'UserCreatedNotification', 'language_key' => 'password_creation'],
            ['notification_type' => 'UserCreatedNotification', 'language_key' => 'password_creation_link'],
            ['notification_type' => 'UserCreatedNotification', 'language_key' => 'password_creation_end_msg'],
            ['notification_type' => 'UserCreatedNotification', 'language_key' => 'best_regards'],
            ['notification_type' => 'UserCreatedNotification', 'language_key' => 'company_name'],

            ['notification_type' => 'UserDetailsNotification', 'language_key' => 'account_details_subject'],
            ['notification_type' => 'UserDetailsNotification', 'language_key' => 'welcome_greeting'],
            ['notification_type' => 'UserDetailsNotification', 'language_key' => 'account_details_message'],
            ['notification_type' => 'UserDetailsNotification', 'language_key' => 'email'],
            ['notification_type' => 'UserDetailsNotification', 'language_key' => 'password'],
            ['notification_type' => 'UserDetailsNotification', 'language_key' => 'login_instruction'],
            ['notification_type' => 'UserDetailsNotification', 'language_key' => 'login_action'],
            ['notification_type' => 'UserDetailsNotification', 'language_key' => 'best_regards'],
            ['notification_type' => 'UserDetailsNotification', 'language_key' => 'company_name'],
            ['notification_type' => 'UserDetailsNotification', 'language_key' => 'disclaimer'],

            ['notification_type' => 'YourAccountIsDisConnected', 'language_key' => 'account_not_connected_subject'],
            ['notification_type' => 'YourAccountIsDisConnected', 'language_key' => 'hello'],
            ['notification_type' => 'YourAccountIsDisConnected', 'language_key' => 'view_details'],
            ['notification_type' => 'YourAccountIsDisConnected', 'language_key' => 'account_not_connected_message'],
            ['notification_type' => 'YourAccountIsDisConnected', 'language_key' => 'account_not_connected_instructions'],
            ['notification_type' => 'YourAccountIsDisConnected', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'YourAccountIsDisConnected', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'YourAccountIsDisConnected', 'language_key' => 'best_regards'],
            ['notification_type' => 'YourAccountIsDisConnected', 'language_key' => 'company_name'],

            ['notification_type' => 'CustomResetPasswordNotification', 'language_key' => 'password_reset_subject'],
            ['notification_type' => 'CustomResetPasswordNotification', 'language_key' => 'hello'],
            ['notification_type' => 'CustomResetPasswordNotification', 'language_key' => 'password_reset_subject'],
            ['notification_type' => 'CustomResetPasswordNotification', 'language_key' => 'password_reset_request'],
            ['notification_type' => 'CustomResetPasswordNotification', 'language_key' => 'reset_password_action'],
            ['notification_type' => 'CustomResetPasswordNotification', 'language_key' => 'password_reset_notice'],
            ['notification_type' => 'CustomResetPasswordNotification', 'language_key' => 'password_reset_expiry'],
            ['notification_type' => 'CustomResetPasswordNotification', 'language_key' => 'best_regards'],
            ['notification_type' => 'CustomResetPasswordNotification', 'language_key' => 'company_name'],

            ['notification_type' => 'NotificationInviteFriend', 'language_key' => 'invite_friend_subject'],
            ['notification_type' => 'NotificationInviteFriend', 'language_key' => 'hello'],
            ['notification_type' => 'NotificationInviteFriend', 'language_key' => 'invite_friend_description'],
            ['notification_type' => 'NotificationInviteFriend', 'language_key' => 'contact_on_telegram'],
            ['notification_type' => 'NotificationInviteFriend', 'language_key' => 'telegram_link'],
            ['notification_type' => 'NotificationInviteFriend', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'NotificationInviteFriend', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'NotificationInviteFriend', 'language_key' => 'best_regards'],
            ['notification_type' => 'NotificationInviteFriend', 'language_key' => 'company_name'],
            ['notification_type' => 'NotificationInviteFriend', 'language_key' => 'disclaimer'],

            ['notification_type' => 'CleanupForUserNotification', 'language_key' => 'account_deleted_subject_user'],
            ['notification_type' => 'CleanupForUserNotification', 'language_key' => 'hello'],
            ['notification_type' => 'CleanupForUserNotification', 'language_key' => 'account_deleted_user_message'],
            ['notification_type' => 'CleanupForUserNotification', 'language_key' => 'best_regards'],
            ['notification_type' => 'CleanupForUserNotification', 'language_key' => 'company_name'],

            ['notification_type' => 'NotificationMarginRisk', 'language_key' => 'margin_risk_subject'],
            ['notification_type' => 'NotificationMarginRisk', 'language_key' => 'hello'],
            ['notification_type' => 'NotificationMarginRisk', 'language_key' => 'margin_risk_description'],
            ['notification_type' => 'NotificationMarginRisk', 'language_key' => 'unsubscribe'],
            ['notification_type' => 'NotificationMarginRisk', 'language_key' => 'unsubscribe_text'],
            ['notification_type' => 'NotificationMarginRisk', 'language_key' => 'best_regards'],
            ['notification_type' => 'NotificationMarginRisk', 'language_key' => 'company_name'],
            ['notification_type' => 'NotificationMarginRisk', 'language_key' => 'disclaimer'],
            
        ]);
    }

    public function down()
    {
        Schema::dropIfExists('notification_language_keys');
    }
}
